language: python
python:
  - "3.6"
sudo: false
os:
  - linux
install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
  - leanpkg configure
  - pushd _target/deps/mathlib/
  - echo y | sh scripts/setup-dev-scripts.sh --global
  - popd
  - source $HOME/.profile
  - update-mathlib
jobs:
  include:
    - env: TASK="check build"
      language: sh
      script:
        - leanpkg build
